# name: Deploy to EC2
# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2
    #   with:
    #     ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # - name: Deploy to EC2
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USERNAME }}
    #     private-key: ${{ secrets.EC2_PRIVATE_KEY }}
    #     # ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       cd lativ-project 
    #       pm2 start ecosystem.config.js --only app

# name: Deploy to EC2
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Setup SSH
#       run: |
#         echo "${{ secrets.EC2_PRIVATE_KEY }}" | tr -d '\r' | sudo ssh-add ~/.ssh/id_rsa

#     - name: Deploy to EC2
#       run: |
#         ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
#         git pull


# name: Deploy to EC2
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Setup SSH
#       run: |
#         echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2.pem
#         chmod 600 ec2.pem
#     - name: Deploy to EC2
#       run: |
#         eval `ssh-agent`
#         sudo ssh-add ~/.ssh/ec2.pem
#         # ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
#         ssh -i ec2.pem ec2-user@${{ secrets.EC2_IP }}

name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup SSH
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2.pem
        chmod 600 ec2.pem
    # - name: Add EC2 host to known_hosts 
    #   run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> /.ssh/known_hosts
    - name: Deploy
      run: | 
        ssh -t -t -i ec2.pem -l ec2-user ${{ secrets.EC2_HOST }}






