name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2
    #   with:
    #     ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        private-key: ${{ secrets.EC2_PRIVATE_KEY }}
        # ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # git pull
          pm2 start ecosystem.config.js --only app

# name: Deploy to EC2
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Setup SSH
#       run: |
#         echo "${{ secrets.EC2_PRIVATE_KEY }}" | tr -d '\r' | sudo ssh-add ~/.ssh/id_rsa

#     - name: Deploy to EC2
#       run: |
#         ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
#         git pull
