name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
      - name: Configure SSH & EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
            HOSTNAME : ${{ secrets.EC2_HOST  }}
            USER_NAME : ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >> ~/.ssh/config 
          <<END
          Host ec2
            HostName $HOSTNAME
            User $USER_NAME
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
      - name: List home directory
        run: |
          git pull
          pm2 start ecosystem.config.js --only app

        






